### ISSUE TITLE
How to handle error in nuxtServerInit?

### ISSUE THREAD

**Issue by iamdubx** [nuxt/nuxt.js#2772]
```js
async nuxtServerInit ({ commit, state }) {
    let sections = await axios.get(`http://api.example.com/sections`)
    commit('SET_SECTIONS', sections.data)
  }
```

Is there any way to handle this kind of error? I want to show user error page.
Docs says

```
The context is given to nuxtServerInit as the 2nd argument, it is the same as the data or fetch method except that context.redirect() and context.error() are omitted.

```

**Comment by clarkdo** [comment]
You can wrap the method with a `try catch` and handle the error by yourself, only if the error is thrown, the error page will be shown

**Comment by iamdubx** [comment]
@clarkdo the reason I ask it's because `error` doesn't work. 

`context.error() are omitted`

**Comment by iamdubx** [comment]
```js
async nuxtServerInit ({ commit }) {
    try {
      let sections = await axios.get(`http://api.cryptomag.online/sections`)
      commit('SET_SECTIONS', sections.data)
    } catch (err) {
      console.error('Error on [nuxtServerInit] action.', err)
    }
  }
```

**Comment by clarkdo** [comment]
Use  `context.error`, it should work now, I will discuss with team about the doc.

```js
  nuxtServerInit({ commit }, { error }) {
    error('Error on [nuxtServerInit] action.')
  }
```

**Comment by clarkdo** [comment]
I have talked to team, you can be free to use `context.error` now, we will update doc soon.

**Comment by iamdubx** [comment]
@clarkdo thank you, this is beautiful! Working like a charm. Error handling in Nuxt are super-cool.

**Comment by iamdubx** [comment]
Now the last thing bothers me about Error handling - is Error layout transition. I just can't find the solution how to make it work smoothly. I tried to switch `modes` but still Error layout appears on the page while Default layout is still present.
