### ISSUE TITLE
AdminLTE 2 (Bootstrap 3) theme and <nuxt-link> issue

### ISSUE THREAD

**Issue by wett1988** [nuxt/nuxt.js#416]
I have a issue with nuxt-link on static nuxt app.

I want to use AdminLTE theme. It based on bootstrap 3.
When i use 'nuxt dev' - nodejs server routes - all works fine, but when a use static app routes - bootsrap dropdowns not works

GIF for illustrate what
http://g.recordit.co/ipCTDDvMQi.gif

If page force reload in browser   - dropdown became works again

It is issue or i doing somebody wrong?

**Comment by ausir0726** [comment]
It possible be your dropdown replace a new element by vue ( dropdown not in layout )
but you don't rebind click event ( use jquery ? )
I think if you keep the same dropdown element at layout , and without change layout
that should be working , but I suggest rewrite [bootstrap-vue](https://github.com/bootstrap-vue/bootstrap-vue) that will be better.

I just add jquery and bootstrap in nuxt.config.js
```
head: {
    ....
    script: [
      { src: 'https://code.jquery.com/jquery-3.1.1.slim.min.js' },
      { src: 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js' }
    ],
  },
```
and write dropdown in `layouts/default.vue`

![dropdown](https://cloud.githubusercontent.com/assets/7247064/24210647/b2102cbe-0f64-11e7-9b1f-10c8d7099b66.gif)

**Comment by wett1988** [comment]
@ausir0726 yes, this works because it run by 'nuxt dev' server. - it works for me to.

I'm talking about the case when used 'nuxt generate' - static version of nuxt app.

**Comment by ausir0726** [comment]
umm...

but I tried generate works for me . 
anyway ,
I wiil try to find some information for help ..
if you can upload your project code to github , that will be easier for test ..

![dropdown](https://cloud.githubusercontent.com/assets/7247064/24225926/4144208c-0f9e-11e7-94ab-23fc6ef94f8a.gif)

**Comment by wett1988** [comment]
@ausir0726 Thank you! I am very grateful for your help!

I created a repository with minimal AdminLTE template

https://github.com/wett1988/tmp_adminlte_nuxtjs

the problem still remained

**Comment by ausir0726** [comment]
hi , I found why your problem .

that because you write `type: 'text/javascript'` attribute , so it broken after you change route .

first time you really loaded bootstrap.js and bind dropdown event.
but , when you change the route , vue-meta change something in head tag
origin script bootstrap is remove and bind a new one ...
so , your dropdown already bind the function in origin bootstrap.js
now , it's gone ......  so ,,
every time you click dropdown , the `aria-expanded` always give you `false`

if you remove `type: 'text/javascript'` , dropbox will be work ok when you change route .
but I don't know why we write `type: 'text/javascript'` , vue-meta create a new script ..

finally , I will suggest you remove the bootstrap.min.js and find the source code ,
rewrite the vue component version will be best .

![dropdown](https://cloud.githubusercontent.com/assets/7247064/24248494/af6b2990-100a-11e7-92aa-ecd000b917e2.gif)

**Comment by ausir0726** [comment]
@alexchopin 
I think is a another html-minifier issue with nuxt.js
because , when generate will html minify , it default will remove `type='text/javascript'` tag
so vue-meta will replace a new script .

**Comment by wett1988** [comment]
> that because you write type: 'text/javascript' attribute , so it broken after you change route .

Yes! It works! Thank you so much! I would never have guessed that the problems in this strange behavior

> I don't know why we write type: 'text/javascript' , vue-meta create a new script

The developers recently [wrote](https://twitter.com/nuxt_js/status/836898922337566721) in the release version 1.0, they add support of `vue-meta` - perhaps with this library will not be such a strange behavior

**Comment by ausir0726** [comment]
@wett1988  It seen like html minify issue . 
I think that will soon be fix .
you should keep the title have bootstrap , change route , nuxt-link .......
that will be easier for other people search :D
I guess no one can understand the vue-meta problem when they have problem .
and this maybe html minify issue 👍

**Comment by wett1988** [comment]
`It seen like html minify issue. I think that will soon be fix .`

Well if the issue is simple and we have helped developers in their large case

> you should keep the title have bootstrap , change route , nuxt-link ....... that will be easier for other people search :D

I thought that developers so it will be easier to understand that the problem is not that someone wrote the code, and that the product of the real issue

Ok, i will return old title :)

**Comment by Atinux** [comment]
I will be fixed in the upcoming release and the `html-minifier` options will be customisable via `nuxt.config.js` 👍 

Thank you @ausir0726 for helping!

**Comment by Atinux** [comment]
The [0.10](https://github.com/nuxt/nuxt.js/releases/tag/v0.10.0) release it out ✋
