### ISSUE TITLE
no scrollBehavior on route-change with nested nuxt-child

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxt.js#4404]
### Version

[v2.3.2](https://github.com/nuxt.js/releases/tag/v2.3.2)

### Reproduction link

[https://github.com/davidpmccormick/btmat-nuxt](https://github.com/davidpmccormick/btmat-nuxt)

### Steps to reproduce
1. scroll down this page: http://next.btmat.org.uk/2012
2. click on an article excerpt link
3. see the article render half way down the page

[Here's the repo](https://github.com/davidpmccormick/btmat-nuxt)

Both the [`from` page](https://github.com/davidpmccormick/btmat-nuxt/blob/master/pages/_year.vue) and the [`to` page](https://github.com/davidpmccormick/btmat-nuxt/blob/master/pages/_year/_month/_pageSlug.vue) include `scrollToTop: true`.

Related: #2738
cc @davidpmccormick 

### What is expected ?

scrollBehavior is triggered

### What is actually happening?

scrollbehavior is not triggered (no scrollToTop)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8200">#c8200</a>)</em></sub></div>

**Comment by manniL** [comment]
Fixed if you use an `index.vue` file in the subfolder. (PR incoming for the repo)

**Comment by davidpmccormick** [comment]
@manniL I found I was having the same issue on another page so attempted to replicate what you had done in davidpmccormick/btmat-nuxt#1 – basically changing a `_pageSlug.vue` file to an `index.vue` inside a `_pageSlug` directory ([see here](https://github.com/davidpmccormick/btmat-nuxt/blob/master/pages/_year/_month/_pageSlug/index.vue)).

But while I can see the `routeChanged` even being emitted, and `scrollToTop: true` is on the route, this page doesn't scroll to the top after clicking the final news promo on the page ('Breastmilk banks') https://btmat.org.uk/2012/11/breastmilk-bomb

This appears only to be an issue when the news item is from the same `year/month`.

Any other ideas?

**Comment by manniL** [comment]
@davidpmccormick for the latter, use `watchQuery`

**Comment by davidpmccormick** [comment]
The pagination relies on a path parameter (`/page/x`) rather than a query string, so I don't think `watchQuery` is the right fit.

It's like this because I didn't want to change the URL structure of an old WordPress install (I'd have used a query for pagination if I was setting it up from scratch).

**Comment by davidpmccormick** [comment]
What's the right approach for bug reporting on this? I don't want to just open another issue, but would really like to try and figure out why `triggerScroll` still isn't getting called after `routeChanged` for certain routes.

**Comment by manniL** [comment]
@davidpmccormick I'd suggest to open a new Issue with a *minimal* reproduction repo again.
