### ISSUE TITLE
HTMLElement is not defined in start app.

### ISSUE THREAD

**Issue by 1benayatei** [nuxt/nuxt.js#5622]
I installed it nuxt js on universal mode and install element-ui but when run npm run build and npm run start Throw error:

![image](https://user-images.githubusercontent.com/20650109/56891226-08af0200-6a91-11e9-8a4c-1e75a2eb4ed8.png)

**Comment by pjt57364413** [comment]
how to fix? i has the  error to

**Comment by trylovetom** [comment]
same here

**Comment by clarkdo** [comment]
This issue is fixed in element-ui https://github.com/ElemeFE/element/pull/15277 

Should be included in element-ui next release: element-ui@2.8.3

**Comment by pjt57364413** [comment]
thank you 57364413 邮箱：57364413@qq.com 签名由 网易邮箱大师 定制 On 05/01/2019 22:18, Xin Du (Clark) wrote: This issue is fixed in element-ui ElemeFE/element#15277 Should be included in element-ui next release: element-ui@2.8.3 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by lanxuebao** [comment]
I also encountered this problem. After consulting the Element-Ui source code, I came to the conclusion that you should use a version less than 2.8.2.

**Comment by lanxuebao** [comment]
package.json

**Comment by lanxuebao** [comment]
package.json
"element-ui": "=2.7.2"

**Comment by robbygallo** [comment]
I have the same issue.
I have already tried different version
2.8.2
2.7.2
2.4.11 (default)

but the error still be there...

**Comment by F145h** [comment]
have this issue with 2.8.2 version.
But afer uninstall(npm uninstall element-ui) and install 2.4.11(npm install element-ui@2.4.11) the problem was solved

**Comment by F145h** [comment]
> I have the same issue.
> I have already tried different version
> 2.8.2
> 2.7.2
> 2.4.11 (default)
> 
> but the error still be there...

have this issue with 2.8.2 version.
But afer uninstall(npm uninstall element-ui) and install 2.4.11(npm install element-ui@2.4.11) the problem was solved

**Comment by minatocou** [comment]
nuxt.config.js 
global.HTMLElement = typeof window === 'undefined' ? Object : window.HTMLElement

**Comment by clarkdo** [comment]
For users who are having this issue:

**This issue has been fixed in element-ui ElemeFE/element#15277**
**The fix will be released in element-ui@2.8.3**

For any further question, please comment in https://github.com/ElemeFE/element/issues/15261

**Comment by 1benayatei** [comment]
Has ok in element-ui 2.4.6.

**Comment by arcadesso** [comment]
> > **NOTE** This issue has been fixed in element-ui [ElemeFE/element#15277](https://github.com/ElemeFE/element/pull/15277)
> > The fix will be released in **element-ui@2.8.3**
> 
> For users who are having this issue:
> 
> **Issue fix will be released in element-ui@2.8.3 with [ElemeFE/element#15277](https://github.com/ElemeFE/element/pull/15277)**
> 
> **For any further question, please comment in [ElemeFE/element#15261](https://github.com/ElemeFE/element/issues/15261)**

When is the release planned for version 2.8.3?

**Comment by clarkdo** [comment]
@arcadesso I think you may ask in element-ui repository.

**Comment by andriyfm** [comment]
> > I have the same issue.
> > I have already tried different version
> > 2.8.2
> > 2.7.2
> > 2.4.11 (default)
> > but the error still be there...
> 
> have this issue with 2.8.2 version.
> But afer uninstall(npm uninstall element-ui) and install 2.4.11(npm install element-ui@2.4.11) the problem was solved

it worked for my project. thanks

**Comment by hanpanapn** [comment]
it's bug ,you can use   :   npm install element-ui@2.0.6

**Comment by ptkdev** [comment]
> nuxt.config.js
> global.HTMLElement = typeof window === 'undefined' ? Object : window.HTMLElement

Thanks, work!
