### ISSUE TITLE
Head scripts are reappended and therefore reexecuted on navigation

### ISSUE THREAD

**Issue by guanzo** [nuxt/nuxt.js#5814]
### Version

[2.7.1](https://github.com/nuxt.js/releases/tag/2.7.1)

### Reproduction link

[https://github.com/guanzo/codesandbox-nuxt](https://github.com/guanzo/codesandbox-nuxt)

### Steps to reproduce

$ git clone https://github.com/guanzo/codesandbox-nuxt nuxtbug

$ cd nuxtbug

$ npm i

$ npm run generate

$ npx http-server dist

Open the webpage and dev tools, go to the Elements tab, expand the ` <head>` node

Note the position of the element
```
<script data-n-head="true" src="https://arc.io/widget.js?MURGrEjPmB6gVvzyvpbDut" async=""></script>
```

Note the element `<div id="arc-widget"></div>` at the bottom of `<body>`. This element is created when the `arc.io/widget.js` script is loaded.

Click the "test" link

The `<head>` is updated and the script has been appended to the bottom of  `<head>`, causing it to execute again, and now there are 2 `#arc-widget` elements.

### What is expected ?

A script is loaded once across all navigations.

### What is actually happening?

A script is loaded twice across all navigations.

### Additional comments?

Related to https://github.com/nuxt/nuxt.js/issues/3396.

This only occurs when each nuxt page has its own title. When nuxt updates the page title on navigation, the script is reappended. The `hid` attribute on the script tag doesn't fix it.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9269">#c9269</a>)</em></sub></div>

**Comment by rchl** [comment]
@pimlie 

Script in generated page has this outerHTML:
```
<script data-n-head="true" src="..." async></script>
```
while dynamically created script has this:
```
<script data-n-head="true" src="..." async="true"></script>
```
so then those fail `isEqualNode` check in here:
https://github.com/nuxt/vue-meta/blob/2775c2dfd9b5a0752a71df780f5f3fc97942ffb8/src/client/updaters/tag.js#L63
because `async` attribute value is different.

SSR page when using `npm run dev` works fine (has `async="true"` in source).

**Comment by pimlie** [comment]
@guanzo I am afraid I cant reproduce this on csb. As in the widget.js script doesnt move to the end of head, for me it stays at the same position as after the page has loaded and the div is only listed once.

@rchl Please try vue-meta the rc for v2 as that should be fixed in v2

**Comment by rchl** [comment]
@pimlie But I don't think you can reproduce that on CSB as this bug only reproduces with `nuxt generate`. I've created maybe more clear version of original repro at https://github.com/rchl/nuxt-generate-meta-bug . You could give it a try maybe? Need to follow instructions in the readme.

And sorry but I haven't tested v2 rc as I have troubles figuring out how to plug in that version into existing dependencies. Tried linking vue-app and vue-renderer from my local nuxt checkout but got `Unexpected token export` errors.

**Comment by pimlie** [comment]
You can install v2rc by running `yarn add vue-meta@next` (npm lists all available tags for a package you can use on the `XX Versions` tab here: https://www.npmjs.com/package/vue-meta)

I actually did run the generate on csb. I couldnt add extra yarn scripts it seems so I first ran yarn generate, then I changed the generate script in package.json to be the npx command (and added -p 3000) then deliberately added an error to nuxt.config so nuxt dev would fail to run (and port 3000 was available), clicked on yarn generate which now started the http-server et voila :)

**Comment by rchl** [comment]
@pimlie but `yarn add vue-meta@next` doesn't override `vue-meta` sub-dependencies of `vue-app` and `vue-renderer` as far as I can see. It will just install hoisted version but nothing will use it.

Or am I wrong? I can still see references to `vue-meta v1.6.0` in generated files at least.

**Comment by pimlie** [comment]
The quickest way to check if you are running v2 is load your Nuxt app in the browser and check `window.$nuxt._vueMeta`. If that exists (and is an object) then you are using v2.

**Comment by rchl** [comment]
`window.$nuxt._vueMeta` exists and is an object but bug still reproduces.

**Comment by rchl** [comment]
And actually with v2 it reproduces both when using `yarn generate` and `yarn dev` while with v1 it only reproduces with `yarn generate`.
