### ISSUE TITLE
Default create-nuxt-app project generate fails

### ISSUE THREAD

**Issue by DummyCo** [nuxt/nuxt.js#6755]
### Version

[create-nuxt-app v2.12.0](https://github.com/nuxt/create-nuxt-app/releases/tag/v2.12.0)
[nuxt.js 2.10.2](https://github.com/nuxt/nuxt.js/releases/tag/v2.10.2)

### Reproduction link

[https://gist.github.com/DummyCo/adf66b7eb8b904f8f2f2a07c0f341ccf](https://gist.github.com/DummyCo/adf66b7eb8b904f8f2f2a07c0f341ccf)

### Steps to reproduce

1) npx create-nuxt-app nuxt
2) npm run dev
3) npm run generate

### What is expected ?

Generated dist

### What is actually happening?

Error:

```
ERROR   /inspire                                                                                             02:33:49

TypeError: Cannot read property 'props' of undefined
    at D:\projects\nuxt\node_modules\vue\dist\vue.runtime.common.prod.js:6:9329
    at Tt (D:\projects\nuxt\node_modules\vue\dist\vue.runtime.common.prod.js:6:9512)
    at Tt (D:\projects\nuxt\node_modules\vue\dist\vue.runtime.common.prod.js:6:9924)
    at Function.Cn.t.extend (D:\projects\nuxt\node_modules\vue\dist\vue.runtime.common.prod.js:6:30431)
    at l (server.js:1:5043)
    at Object.<anonymous> (server.js:1:28181)
    at r (server.js:1:194)
    at Module.<anonymous> (server.js:1:359590)
    at r (server.js:1:194)
    at Object.<anonymous> (server.js:1:30705)
    at r (server.js:1:194)
    at server.js:1:1284
    at Object.<anonymous> (server.js:1:1294)
    at o (D:\projects\nuxt\node_modules\vue-server-renderer\build.prod.js:1:77605)
    at D:\projects\nuxt\node_modules\vue-server-renderer\build.prod.js:1:78198
    at new Promise (<anonymous>)
```

### Additional comments?

OS: Windows 10

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10076">#c10076</a>)</em></sub></div>

**Comment by igorpopryadukhin** [comment]
Same problem

`rusaddress.nuxt_public |
rusaddress.nuxt_public |  WARN  devModules has been renamed to buildModules and will be removed in Nuxt 3.
rusaddress.nuxt_public |
rusaddress.nuxt_public | ℹ Listening on: http://172.19.0.4:3000/
rusaddress.nuxt_public |
rusaddress.nuxt_public |  ERROR  Cannot read property 'props' of undefined
rusaddress.nuxt_public |
rusaddress.nuxt_public |   at node_modules/vue/dist/vue.runtime.common.prod.js:6:9329
rusaddress.nuxt_public |   at Tt (node_modules/vue/dist/vue.runtime.common.prod.js:6:9512)
rusaddress.nuxt_public |   at Tt (node_modules/vue/dist/vue.runtime.common.prod.js:6:9924)
rusaddress.nuxt_public |   at Function.Cn.t.extend (node_modules/vue/dist/vue.runtime.common.prod.js:6:30431)
rusaddress.nuxt_public |   at l (server.js:1:6028)
rusaddress.nuxt_public |   at Object.<anonymous> (server.js:1:72721)
rusaddress.nuxt_public |   at o (server.js:1:194)
rusaddress.nuxt_public |   at Object.<anonymous> (server.js:1:88910)
rusaddress.nuxt_public |   at o (server.js:1:194)
rusaddress.nuxt_public |   at Module.<anonymous> (server.js:1:459665)
rusaddress.nuxt_public |
`

**Comment by DispatchCommit** [comment]
Also encountering this error

![image](https://user-images.githubusercontent.com/45262335/69957151-df3ad680-14b6-11ea-8df7-30e8869174d1.png)

Here's where the server is throwing the error - but it's so minified I'm not sure of what I'm looking at, and there are no errors when running dev.

![image](https://user-images.githubusercontent.com/45262335/69957439-861f7280-14b7-11ea-9439-646d1c67c9bc.png)

**Comment by gnolmon** [comment]
Same problem when generate static file for server with same line code 9329 and no problem when running nuxt dev

**Comment by DispatchCommit** [comment]
Ok I went back through my last commit that caused this error to occur, reverted it, and I'm able to cause this error just by running `npm install nuxt`. Downgrading nuxt versions after the fact doesn't seem to revert the issue either. Went from 2.9.2 -> 2.10.2 (error happens) -> 2.9.2 and the error remains.

There must be a downstream issue causing this error.

**Comment by igorpopryadukhin** [comment]
The blame for everything **<v-app-bar>**
Empirically became delete components in turn.
There is no error if there is no **<v-app-bar>** in the project

Sorry, I'm weak in English

**Comment by steklopod** [comment]
Same error :-(

**Comment by igorpopryadukhin** [comment]
What are some suggestions to resolve this error?

**Comment by N7k** [comment]
@igorpopryadukhin great investigation! Unfortunately, we're not using '<v-app-bar>`, but we attempted to spot a problematic component in the same way.
Under fuzzy conditions and combinations, we're getting `v-tabs, v-tab, v-tabs-items, v-tab-item, v-card` generate failing too...

**Comment by N7k** [comment]
@igorpopryadukhin great investigation! Unfortunately, we're not using `<v-app-bar>`, but we attempted to spot a problematic component in the same way.
Under fuzzy conditions and combinations, we're getting `v-tabs, v-tab, v-tabs-items, v-tab-item, v-card` generate failing too...

**Comment by kichigai** [comment]
I have same error.
Last week build file is working. But today build file `run start` not working.

**Comment by steklopod** [comment]
I'm also updated at last Node version

**Comment by igorpopryadukhin** [comment]
Is there an option to roll back?

**Comment by lennoximus** [comment]
Rollback to the previous version did the trick for me. Just make sure you are using `npm ci` to install the exact previously working versions of the packages.

**Comment by kichigai** [comment]
I've changed the Dependency version in a variety of ways, everything is fail.
I try `yarn upgrade --latest` just a second, and `run start` working.
There are some suspected errors, but I am not sure and I believe they have been corrected at this time.
Try again

**Comment by lucafaggianelli** [comment]
@kichigai can you share a diff of your package.json to understand which dependency is causing the issue?
I tried to downgrade to nuxt 2.9.2 but I got more errors on any `nuxt` command
```
ERROR in ./.nuxt/client.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] /home/luca/dev/vjago-landing/.nuxt/client.js: Cannot find module './src/data' (While processing: "/home/luca/dev/vjago-landing/node_modules/@nuxt/babel-preset-app/src/index.js")
```

I needed to wipe out `node_modules` and revert `package-lock.json` changes to be able to run `nuxt dev` again.

**Comment by igorpopryadukhin** [comment]
Try it, it works for me | nuxt universal vuetify
[package.zip](https://github.com/nuxt/nuxt.js/files/3913156/package.zip)

**Comment by DispatchCommit** [comment]
I verified earlier today that upgrading or installing `nuxt` in any capacity causes this error. I took a working project and ran `npm upgrade nuxt` (nuxt@2.10.2) and got this error. Down grading to a previously working version will fail also, `npm install nuxt@2.9.2` will still have the error. 

This must be an issue in a dependency of `nuxt` since a downgrade does *not* fix the error, but `npm ci` does  since the dependency versions don't change with `npm ci`.

How can we isolate and diagnose the faulty dependency?  I'll throw my working [`package-lock.jsob`](https://github.com/bitwave-tv/bitwave/blob/dev/package-lock.json) in the mix in case anyone wants to diff various ones. Here is the broken [`package-lock.json`](https://github.com/bitwave-tv/bitwave/blob/3bd86af98a79756ba650a4b039622c3aa9c786b2/package-lock.json)

I can also confirm that thankfully `dev` mode works fine still, but build & run/start error out. 

Does anyone have any hunches on a package that could cause this? Since this appears to be related to SSR / Site generation, I don't think there is going to be any way to prevent the error from the side of nuxt our Vue related source code lives in. 

The fact that downgrading nuxt isn't even a surefire fix for this error and that even old versions of nuxt show regression also makes this error a showstopper.

**Comment by igorpopryadukhin** [comment]
I played around with downgrading, it did not produce results.

Next, I turned to an old, abandoned project.
Extracted **package-lock.json** and **put package.json** into the problematic project.
Next npm ci.

Then he manually upgraded the version **@ nuxtjs/vuetify** to ^ 1.9.0 and performed **npm install**

More errors not observed!

[Dependencies](https://github.com/nuxt/nuxt.js/issues/6755#issuecomment-560563944)

**Comment by kichigai** [comment]
@lucafaggianelli 
I try dependency update from last `run start` working source.
There was no problem if the update was specified for individual dependency update.
But, It's not working using `yarn upgrade --latest` or clean dependency install.
I compared dependency list before and after the change. (`yarn list`).
When using `yarn upgrade --latest` or clean dependency install (`rm -fR node_modules` and `yarn install`) some dependency upgraded new version.
But I couldn't find cause dependency.
I gave up looking for a problem and ran `yarn upgrade --latest` and it worked.
And, I found some new dependency version.

**Comment by JTBrinkmann** [comment]
In my case, I managed to fix the issue by upgrading to the current version 2.10.2 with `npm upgrade nuxt` (or `npm install nuxt@2.10.2`)

@DummyCo in the ticket you wrote that you observed the issue with **2.12.0**. I assume that was a typo, as that version doesn't seem to exist yet?

**Comment by DummyCo** [comment]
@JTBrinkmann, yeah, that was **2.12.0** for create-nuxt-app and **2.10.2** for nuxt.js. Fixed that in ticket description, thank you!

**Comment by steklopod** [comment]
After removing ‘node min’ from devDependencies everything works fine. 🤯🤔

**Comment by Mann-o** [comment]
I was having similar issues, narrowed the problem down to a faulty version of `core-js-compat` (dependency of `@babel/preset-env`) which has since been fixed.

I use Yarn so I have temporarily pinned `core-js-compat` to the latest version and this has resolved all issues:
```
"resolutions": {
  "core-js-compat": "3.4.7"
}
```

**Comment by DummyCo** [comment]
Can confirm that `2.10.1` rollback works:
```
npm install nuxt@2.10.1
npm ci
```

**Comment by DummyCo** [comment]
Can confirm that clean `2.10.1` rollback works:
```
npm install nuxt@2.10.1
npm ci
```

**Comment by igorpopryadukhin** [comment]
> Can confirm that `2.10.1` rollback works:
> 
> ```
> npm install nuxt@2.10.1
> npm ci
> ```

I did not check, but it definitely works with `nuxt@2.9.1`

**Comment by lucafaggianelli** [comment]
I'm losing my brain sanity! I reverted to 2.8.1 and it was working (apparently), but now it generates (without errors) a blank app, that is, pages are compiled correctly to `.js` files but the content is not loaded and I'm left with `<body>` and an empty `<div>`, see here: https://vjago.com/

Anyone experiencing this?

**Comment by aldarund** [comment]
I think its caused by publishing issue of core-js. https://github.com/zloirock/core-js/releases/tag/v3.4.7
If someone still have it -> try to update your deps e.g. make  sure  "core-js-compat": "3.4.7"

**Comment by aldarund** [comment]
closing as seems to be resolved, in case opne new issue
