### ISSUE TITLE
multiple nuxt instances in layout

### ISSUE THREAD

**Issue by vana-dev** [nuxt/nuxt.js#7552]
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://nuxtjs.org/](https://nuxtjs.org/)

### Steps to reproduce

Weird thing, I have double nuxt instance in my defalut layout, this is my default.vue file

![2.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/926d09b0-b19e-11ea-8f9d-b90f9ab7948d.png)

I tried multiple combinations, I noticed that when I move <nuxt /> to the bottom of parent div, this problem disappear, and everything works fine.

![4.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/d9b7ec40-b19e-11ea-8f9d-b90f9ab7948d.png)

What could be the reason?

### What is expected ?

![1.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/5463e250-b19f-11ea-8f9d-b90f9ab7948d.png)

### What is actually happening?

![3.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/575499a0-b19f-11ea-8f9d-b90f9ab7948d.png)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10792">#c10792</a>)</em></sub></div>

**Comment by simplenotezy** [comment]
I believe this could be related to https://github.com/nuxt/nuxt.js/issues/5615 which is fixed in the latest version

**Comment by vana-dev** [comment]
same problem in v2.13.0

**Comment by vana-dev** [comment]
![Zrzut ekranu 2020-06-20 o 11 07 17](https://user-images.githubusercontent.com/884763/85198104-3d5dc880-b2e6-11ea-8f6e-1744469e4703.png)

simple fix, and problem solved, but still this is a bug not solved in latest release
https://github.com/nuxt/nuxt.js/issues/5703

**Comment by LuisManuelNR** [comment]
i change <nuxt /> to <router-view /> and it seems to fix it

**Comment by davidlandais** [comment]
> ![Zrzut ekranu 2020-06-20 o 11 07 17](https://user-images.githubusercontent.com/884763/85198104-3d5dc880-b2e6-11ea-8f6e-1744469e4703.png)
> 
> simple fix, and problem solved, but still this is a bug not solved in latest release
> #5703

Wrap inside a div doesn't work for me :/ I have also this bug in 2.13.3
![Capture d’écran 2020-07-15 à 10 23 33](https://user-images.githubusercontent.com/2110040/87526287-f5cf2000-c68a-11ea-8249-a8beddcea051.png)
If the page is rendered server-side with a specific layout like "guest", then the page is changed with another layout like "authenticated", nuxt will not render multiple times the layout. But if I enter directly on the page (with the layout "authenticated"), the bug is happening.
